config:
  send_anonymous_usage_stats: False

default:
  outputs:

    dev: # User-Password config
      type: snowflake
      account: dm85224.ca-central-1.aws
      user: DBT_CLOUD_DEV
      password: Knowledge#1
      role: TRANSFORMER_DEV
      database: DEV
      warehouse: TRANSFORMING_DEV
      schema: DBT_SCHEMA 
      threads: 2
      client_session_keep_alive: False

  target: dev
