name: push_to_main

#on:
  #push:
  #  branches:
  #    - main
on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:


env:
  DBT_PROFILES_DIR: ./

  DBT_DEV_DB: "FS_OWNRSHP_TEST_SHIMITH"
  DBT_DEV_PASSWORD: ${{ secrets.DBT_PASSWORD_DEV }}
  DBT_DEV_ROLE: ${{ secrets.DBT_ROLE_DEV }}
  DBT_DEV_SCHEMA: ${{ secrets.DBT_SCHEMA_DEV }}
  DBT_DEV_USER: ${{ secrets.DBT_USER_DEV }}
  DBT_DEV_WH: ${{ secrets.DBT_WH_DEV }}

jobs:
  push_to_main:
    name: main
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Authenticate using service account
        run: 'echo "$KEYFILE" > ./dbt-service-account.json'
        shell: bash
        env:
          DBT_PROFILES_DIR: ./

          DBT_DEV_DB: ${{ secrets.DBT_DB_DEV }}
          DBT_DEV_PASSWORD: ${{ secrets.DBT_PASSWORD_DEV }}
          DBT_DEV_ROLE: ${{ secrets.DBT_ROLE_DEV }}
          DBT_DEV_SCHEMA: ${{ secrets.DBT_SCHEMA_DEV }}
          DBT_DEV_USER: ${{ secrets.DBT_USER_DEV }}
          DBT_DEV_WH: ${{ secrets.DBT_WH_DEV }}

      - name: Install dependencies
        run: |
          pip install dbt-snowflake
          dbt deps #--target prod
      
      # Add dbt seed or other commands here if needed
      - name: Run dbt models
        run: dbt run --selector snowplow_web

      - name: Test dbt models
        run: dbt test --selector snowplow_web